CSS:
  indent_char: " "
  indent_size: 2
  remove_trailing_whitespace: true
  beautifiers: ["stylelint"]
HTML:
  indent_char: " "
  indent_size: 2
  brace_style: "collapse-preserve-inline"
  beautifiers: ["JS-Beautify"]
JavaScript:
  indent_char: " "
  indent_size: 2
  remove_trailing_whitespace: true
  brace_style: "collapse-preserve-inline"
  beautifiers: ["ESLint", "JS-Beautify"]