version: '3.7'

services:
  webapp:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    image: anhphung75/web_hoso:fe02
    working_dir: /home/app/web
    command: python webapp.py --port=8888
    volumes:
      - certs_data:/home/app/web/ssl_cert
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - ./services/web/:/home/app/web/
      - ./fe/public/:/home/app/web/static/js
    ports:
      - 8888:8888

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    image: anhphung75/nginx_hoso:fe02
    volumes:
      - certs_data:/home/app/web/ssl_cert
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
      - 443:443
    depends_on:
      - webapp

volumes:
  certs_data:
  static_volume:
  media_volume: