version: '3.7'

services:
  webapp:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    image: anhphung75/web_hoso:fe02
    command: python webapp.py
    volumes:
      - ./services/web/:/usr/src/app/
      - ./fe/public/:/usr/src/app/static/js
    ports:
      - 8888:8888