version: '3.7'

services:
  webapp:
    build:
      context: ./services/web
      dockerfile: Dockerfile.ubuntu
    image: anhphung75/web_hoso:fe02
    container_name: webapp
    working_dir: /home/app/web
    command: python webapp.py --port=8888
    volumes:
      - certs_data:/home/app/web/ssl_cert
      - static_volume:/home/app/web/static
      - ./services/web/:/home/app/web/
      - ./fe/public/:/home/app/web/static/js
    ports:
      - 8000:8000
    hostname: hoso
    domainname: pkh.cntd

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    image: anhphung75/nginx_hoso:fe02
    container_name: nginx
    volumes:
      - certs_data:/home/app/web/ssl_cert
      - static_volume:/home/app/web/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - webapp

volumes:
  certs_data:
  static_volume:

