version: '3.7'

services:
  webapp:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    image: anhphung75/web_hoso:fe02
    working_dir: /home/app/web
    command: python webapp.py
    volumes:
      - ./services/web/:/home/app/web/
      - ./fe/public/:/home/app/web/static/js
    ports:
      - 8888:8888