version: '3.7'

services:
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    image: anhphung75/fe:nov08
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - '5000:5000'
    working_dir: /usr/src/app
    volumes:
      - ./fe:/usr/src/app
  
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    image: anhphung75/web_hoso:nov08
    command: python webapp.py
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 8888:8888
    env_file:
      - ./.env.web
    depends_on:
      - db
  
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
