version: '3.7'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    image: anhphung75/web_hoso:nov08
    command: python webapp.py
    volumes:
      - ./services/web/:/usr/src/app/
      - ./fe/public/:/usr/src/app/static
    ports:
      - 8888:8888
    env_file:
      - ./.env.web
