version: '3.7'

services:
  svfedora:
    build:
      context: ./services/webapp
      dockerfile: Dockerfile.fedora
    image: anhphung75/hoso1:mar09
    container_name: webapp1
    volumes:
      - certs_data:/home/web/ssl_cert
      - static_volume:/home/web/static
      - ./services/webapp/:/home/web/
      - ./fe/public/:/home/web/static/js
    ports:
      - 8000:8000
    hostname: hoso
    domainname: pkh.cntd

  svubuntu:
    build:
      context: ./services/webapp
      dockerfile: Dockerfile.ubuntu
    image: anhphung75/hoso2:mar09
    container_name: webapp2
    volumes:
      - certs_data:/home/web/ssl_cert
      - static_volume:/home/web/static
      - ./services/webapp/:/home/web/
      - ./fe/public/:/home/web/static/js
    ports:
      - 8001:8001
    hostname: hoso
    domainname: pkh.cntd
    
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    image: anhphung75/nginx_hoso:mar09
    container_name: nginx
    volumes:
      - certs_data:/home/web/ssl_cert
      - static_volume:/home/web/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - svfedora
      - svubuntu

volumes:
  certs_data:
  static_volume:

