version: '3.7'

services:
  svfedora:
    build:
      context: ./services/webapp
      dockerfile: Fedora.dockerfile
    image: anhphung75/hoso1:mar09
    container_name: server1
    ports:
      - 8000:8000
      - 8888:8888
      - 7777:7777

  svfe:
    build:
      context: ./services/fe
      dockerfile: Svelte.dockerfile
    image: anhphung75/fehoso1:mar09
    container_name: svfe1
    ports:
      - 5000:5000

  canbangtai:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    image: anhphung75/canbangtai:mar09
    container_name: canbangtai

