version: '3.7'

services:
  web_app_1:
    image: anhphung75/web_hoso:fe02
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    expose:
      - 8001
    working_dir: /home/app/web
    command: python webapp.py --port:8001
    volumes:
      - certs_data:/home/app/web/ssl_cert
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
  
  can_bang_tai_1:
    image: anhphung75/nginx_hoso:fe02
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web_app_1
      volumes:
        - certs_data:/home/app/web/ssl_cert
        - static_volume:/home/app/web/static
        - media_volume:/home/app/web/media

volumes:
  certs_data:
  static_volume:
  media_volume: