export let tamdskh = [
  {
    mahoso: "2019hs001",
    khachhang: "Nguyen Van A",
    sohoso: "GM01200/19",
    diachi: "123 Tran Van Thoi, Q10",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent'
  },
  {
    mahoso: "2019hs002",
    khachhang: "Pham Van Tuan",
    diachi: "625 Tran Van Thoi, Q11",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs003",
    khachhang: "Tran Van Ty",
    diachi: "1243 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs004",
    khachhang: "Nguyen Thi Nhanh",
    diachi: "125 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs004",
    khachhang: "Nguyen Thi Nhanh",
    diachi: "125 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs004",
    khachhang: "Nguyen Thi Nhanh",
    diachi: "125 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs004",
    khachhang: "Nguyen Thi Nhanh",
    diachi: "125 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs004",
    khachhang: "Nguyen Thi Nhanh",
    diachi: "125 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs004",
    khachhang: "Nguyen Thi Nhanh",
    diachi: "125 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs004",
    khachhang: "Nguyen Thi Nhanh",
    diachi: "125 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs004",
    khachhang: "Nguyen Thi Nhanh",
    diachi: "125 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs004",
    khachhang: "Nguyen Thi Nhanh",
    diachi: "125 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs004",
    khachhang: "Nguyen Thi Nhanh",
    diachi: "125 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs004",
    khachhang: "Nguyen Thi Nhanh",
    diachi: "125 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  },
  {
    mahoso: "2019hs004",
    khachhang: "Nguyen Thi Nhanh",
    diachi: "125 Tran Van Thoi, Q12",
    maq:'01',
    maqp:'0102',
    mota:'',
    ngaygan: '2019/10/20',
    sodhn: '1232',
    chisodhn:0.00,
    madma:'xxx',
    malotrinh:'112',
    trongai:'',
    tainhap:'',
    taithicong:'',
    hoantien:'',
    lienhe:'',
    hieudhn:'kent',
    sohoso:''
  }
];