FROM python:3.8.0

RUN curl https://packages.microsoft.com/config/rhel/8/prod.repo > /etc/yum.repos.d/mssql-release.repo
RUN dnf -y update && dnf -y install python-pip python-devel python-pyodbc
RUN dnf remove unixODBC-utf16 unixODBC-utf16-devel
RUN dnf -y install unixODBC-devel
RUN ACCEPT_EULA=Y dnf -y install msodbcsql17
RUN dnf clean all

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies python
RUN pip install --upgrade pip
WORKDIR /usr/src/app
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# copy project
COPY . /usr/src/app
